export var CLEAR_ORDER = "CLEAR_ORDER";
//Redux constants

export const ADD_ORDER = "ADD_ORDER";
export const ALL_ORDERS = "ALL_ORDERS";
export const GET_PENDING = "GET_PENDING";

//Path signal
export const CHANGE_PATH = "CHANGE_PATH";
export const SET_ROOT_PATH = "SET_ROOT_PATH";
export const SET_ACCOUNTS_PATH = "SET_ACCOUNTS_PATH";
export const SET_ORDERS_PATH = "SET_ORDERS_PATH";
export const SET_ADMIN_PATH = "SET_ADMIN_PATH";

//Current order
export const CHANGE_ORDER_PROPERTY = "CHANGE_ORDER_PROPERTY";
export const CHANGE_PAPER_DETAILS_PROPERTY = "CHANGE_PAPER_DETAILS_PROPERTY";
export const CHANGE_PAPER_INSTRUCTIONS_PROPERTY = "CHANGE_PAPER_INSTRUCTIONS_PROPERTY";
export const CHANGE_PAPER_CALCULATIONS_PROPERTY = "CHANGE_PAPER_CALCULCATIONS_PROPERTY";
export const CHANGE_ADDITIONAL_PROPERTY = "CHANGE_PAPER_ADDITIONAL_PROPERTY";
export const SAVE_ORDER_ANON = "SAVE_ORDER_ANON";
export const SAVE_ORDER = "SAVE_ORDER";
export const COMPLETE_ORDER = "COMPLETE_ORDER";


//Orders form manager
export const CHANGE_ACTIVE_FORM = "CHANGE_ACTIVE_FORM";

//User management
export const SIGN_IN_EMAIL_PASSWORD = "SIGN_IN_EMAIL_PASSWORD";
export const SIGN_UP_EMAIL_PASSWORD = "SIGN_IN_EMAIL_PASSWORD";

//general
export const LOADING_DATA = "LOADING_DATA";
export const FINISH_LOADING_DATA = "FINISH_LOADING_DATA";
export const RECEIVED_USER = "RECEIVED_USER";
export const ERROR = "ERROR";

//path management
export const CHANGE_ACTIVE_PATH = "CHANGE_ACTIVE_PATH";