export const SIGN_UP = '/signup';             //public - Accessible to anyone
export const SIGN_IN = '/signin';                //public
export const LANDING = '/';                     //public || protected - Certain parts are visible based on authentication
export const HOME = '/home';                    //protected - Only accessible to logged in users
export const PASSWORD_FORGET = '/pw-forget';    //public
export const VIEW_ORDERS = '/view-orders';      //protected
export const POST_ORDER = '/post-order';        //public
export const ORDER_DETAILS = '/order';          //protected
export const MESSAGES = "/messages";            //protected
export const NOTIFICATIONS = "/notifications";  //protected